### ISSUE TITLE
Following Markdown Readme instructions results in 404 when calling the endpoint.

### ISSUE THREAD

**Issue by n-ate** [Ignition-Group-Open-Source-Contrib/Dapr-Microservice-Template#12]
Following the readme markdown file, I am able to get the app deployed. It however does not respond on the specified port to the specified get request. I've tried replacing the part of the uri in quotes ("daprid") with everything that I can think of. I've used the specified app id, I've used my project and namespace name, I've used the specified project name. I always receive a 404.

Please help. I've tried deploying dapr services in several ways over the last week and eventually get stuck. I ran across your extension last night and thought it would be easier.

**Comment by malotho** [comment]
Can you share your URL here, I want to make sure the format is correct. 
Are you hosting on AKS on minikube?

**Comment by malotho** [comment]
We can chat on teams as well, and we can debug through the issues together 👍🏿

**Comment by malotho** [comment]
No response
